# Generated by Django 4.2.7 on 2023-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=255)),
                ("joining_date", models.DateField(auto_now=True)),
                ("salary", models.DecimalField(decimal_places=3, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deactive", "deactive")],
                        max_length=9,
                    ),
                ),
            ],
        ),
    ]
