# Generated by Django 4.2.7 on 2023-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
