# Generated by Django 4.2.7 on 2023-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_joining_date_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], max_length=9, null=True),
        ),
    ]
